name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"           # Runs daily at 6 PM UTC (~11:30 PM IST)
  workflow_dispatch:               # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
